### ISSUE TITLE
Running repo_sync gives me errors recently

### ISSUE THREAD

**Issue by Tim81** [wdas/reposado#76]
Hello, recently I notice that running a repo_sync gives me:

repo_sync run started
Traceback (most recent call last):
  File "/usr/local/asus/reposado/code/repo_sync", line 852, in <module>
    main()
  File "/usr/local/asus/reposado/code/repo_sync", line 848, in main
    download_packages=download_packages)
  File "/usr/local/asus/reposado/code/repo_sync", line 646, in sync
    products = reposadocommon.getProductInfo()
  File "/usr/local/asus/reposado/code/reposadolib/reposadocommon.py", line 311, in getProductInfo
    return getDataFromPlist('ProductInfo.plist')
  File "/usr/local/asus/reposado/code/reposadolib/reposadocommon.py", line 284, in getDataFromPlist
    os.path.join(metadata_dir, filename))
  File "/usr/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/usr/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
  File "/usr/lib/python2.7/plistlib.py", line 418, in handleEndElement
    handler()
  File "/usr/lib/python2.7/plistlib.py", line 470, in end_string
    self.addObject(self.getData())
  File "/usr/lib/python2.7/plistlib.py", line 425, in addObject
    self.stack[-1][self.currentKey] = value
TypeError: list indices must be integers, not str

Not sure why, I've updated to latest source but did not resolve.

Running on Ubuntu 16.04 LTS

**Comment by gregneagle** [comment]
Not seeing this and have had no other reports; I don't know what to suggest for further troubleshooting on your end.

**Comment by arimav** [comment]
I got this exact same issue.

I tried re downloading reposado and deleting my old reposadolib. Ran repo_sync again and got the same result. I'm starting to wonder if python2.7 has anything to do with this.

**Comment by gregneagle** [comment]
Again, not enough info here to do much more than guess, but it seems likely that some of the data reposado has downloaded it doesn't like. Specifically it seems plistlib is choking while reading a file, and in the case of the original poster, the file it's choking on is 'ProductInfo.plist'.

**Comment by arimav** [comment]
well now I feel silly. All I had to do is find 'ProductInfo.plist' file and delete it. Ran repo_sync again and it's all back to normal. Somehow it got corrupted. Thanks for pointing that out.
