### ISSUE TITLE
repo_sync stops with error since Oct.24.

### ISSUE THREAD

**Issue by vasquesbc** [wdas/reposado#78]
this is the output i get:

`Traceback (most recent call last):
  File "/usr/local/bin/repo_sync", line 852, in <module>
    main()
  File "/usr/local/bin/repo_sync", line 848, in main
    download_packages=download_packages)
  File "/usr/local/bin/repo_sync", line 663, in sync
    'Could not replicate %s: %s', catalog_url, err)
  File "/usr/local/bin/reposadolib/reposadocommon.py", line 235, in print_stderr
    output = concat_message(msg, *args)
  File "/usr/local/bin/reposadolib/reposadocommon.py", line 192, in concat_message
    args = [str_to_ascii(arg) for arg in args]
  File "/usr/local/bin/reposadolib/reposadocommon.py", line 185, in str_to_ascii
    return s.decode('ascii', 'ignore')
AttributeError: 'ReplicationError' object has no attribute 'decode'`

any advice what to do about it?
running on Ubuntu 18.04.2.

**Comment by gregneagle** [comment]
I'm not seeing this issue, nor have I had other reported instances. Not sure what to suggest for further troubleshooting on your end.

**Comment by vasquesbc** [comment]
it seams that another reboot of the machine made this ... weird issue disappear.
